version: '3'
services:
  customer:
    build: .
    image: customer
    container_name: customer
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/final_test_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kosafinal
      IMAGE_PROFILE: /data/profile/
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/kosafinal
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka:8080/eureka
    ports:
      - "38000:8080"
    volumes:
      - /volume1/web/imgcache:/data
    networks:
      - kosafinal
networks:
  kosafinal:
    external: true